service: lamda-app

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  environment:
    TABLE_NAME: ${self:custom.DataTable.name}
  iamRoleStatements:
    - ${file(iam/itemsIAM.yml):itemsIAM}
functions:
  getItem:
    handler: src/handlers/getItem.run
    events:
      - http:
          path: /item/{id}
          method: GET
  getItems:
    handler: src/handlers/getItems.run
    events:
      - http:
          path: items
          method: GET
  createItem:
    handler: src/handlers/createItem.run
    events:
      - http:
          path: item
          method: POST
          cors: true

resources:
  Resources:
    DataTable: ${file(resources/items.yml):DataTable}

custom:
  DataTable:
    name: !Ref DataTable
    arn: !GetAtt DataTable.Arn
