DataTable:
  Type: "AWS::DynamoDB::Table"
  Properties:
    TableName: items-${self:provider.stage}
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1
